### ISSUE TITLE
Visualize_saliency breaks for 1D Inputs

### ISSUE THREAD

**Issue by karthikbmk** [raghakot/keras-vis#103]
Bug : Currently, visualize_saliency returns 3D gradients for 1D Inputs.

Possible Fix : In visualize_saliency_with_losses function, replace **return np.uint8(cm.jet(grads)[..., :3] * 255)[0]** with **return grads[0]**

**Comment by ChaitanyaKolluru1** [comment]
This seems to have been fixed in #67. I installed through pip and I see the older version (return np.uint8(cm.jet(grads)[..., :3] * 255)[0]) in my copy. I will try cleaning up my installation and keep you posted.
