### ISSUE TITLE
Guided Back-propagation implementation

### ISSUE THREAD

**Issue by drgarg** [raghakot/keras-vis#11]
This is a useful tool for visualizations. Currently, it is missing from this wonderful library. It complements grad-CAM very well as highlighted in the grad-CAM paper.

**Comment by raghakot** [comment]
Sorry this took so long. It is finally Implemented. I wanted to do this in a clean and flexible way and finally found a satellite scarcity way to incorporate it. Check out the API docs and examples to see th usage.

Currently only the tensorflow version is implemented. Expect theano support to show up within this week.

**Comment by ELVDW** [comment]
Where can I find an example for the implementation for guided back propagation using keras-vis? I checked out the API docs and I could not find any examples. Could someone tell me where to find this?
