### ISSUE TITLE
A problem with tensorflow 1.8.0!

### ISSUE THREAD

**Issue by Avcu** [raghakot/keras-vis#117]
Hi, everyone I had a problem as you can see from the link below and I do not really want anyone to bother him/herself for days like me. Till the next update, don't use last verified version of tensorflow which is 1.8.0 but use 1.7.1. Hopefully someone will take care of it soon. 

https://github.com/raghakot/keras-vis/issues/116

**Comment by keisen** [comment]
Hi, guys.

I created PR( #120 ) so please refer to it.
And... , please merge it soon and release a new version. :-)

**Comment by keisen** [comment]
Duplicate #119

**Comment by raghakot** [comment]
Pushed @keisen PR.
