### ISSUE TITLE
Is master on pip?

### ISSUE THREAD

**Issue by sx5640** [raghakot/keras-vis#118]
Running into an issue with `utils.apply_modifications` on Windows that the temporary directory is not Windows compatible, but I noticed the issue has been addressed on master branch. The current version I can get from pip is `0.4.1` which was released a year ago. Is there a version that I'm missing?

**Comment by keisen** [comment]
I think that the fix has not been released yet.
I installed it directly from master branch.

```
pip install git+https://github.com/raghakot/keras-vis.git
```

**Comment by gafergus** [comment]
Any idea when the fix is going to be released?
