### ISSUE TITLE
[RAGHAVENDRA AND CONTRIBUTORS SEE THIS] Missing a comma on citation

### ISSUE THREAD

**Issue by manuelblancovalentin** [raghakot/keras-vis#121]
This message is directed to the authors of keras-vis. I recently used (and slightly modified) your version of keras-resnet and wanted to cite you on my paper. I just wanted to let you know that your "Citation" tip on the keras-vis page is missing a comma after "@misc{raghakotkerasvis". Without it bibtex will return an error. 

This is what's on your repo readme:

```
@misc{raghakotkerasvis
  title={keras-vis},
  author={Kotikalapudi, Raghavendra and contributors},
  year={2017},
  publisher={GitHub},
  howpublished={\url{https://github.com/raghakot/keras-vis}},
}
```

This is what SHOULD be in order to work on latex:
```
@misc{raghakotkerasvis,
  title={keras-vis},
  author={Kotikalapudi, Raghavendra and contributors},
  year={2017},
  publisher={GitHub},
  howpublished={\url{https://github.com/raghakot/keras-vis}},
}
```
Hope that helped (at least a little as much as your code helped my research!)

**Comment by raghakot** [comment]
Thanks. Fixed.
