### ISSUE TITLE
Issues with saliency map for 1d input

### ISSUE THREAD

**Issue by subhashis** [raghakot/keras-vis#135]
I have a fully connected network with 1d input of size 35 and generates 1d output of size 50. I wanted to compute the saliency map for given inputs for this network. However, the output of the visualize_saliency(... ) function is just returning me an array of size 3 (instead for size 35 i.e. my input size). 

#my model structure
M1.summary()
>
Layer (type)                 Output Shape              Param #   
_________________________________________________________________
input_2 (InputLayer)         (None, 35)                0         
_________________________________________________________________
dense_37 (Dense)             (None, 64)                2304      
_________________________________________________________________
activation_25 (Activation)   (None, 64)                0         
_________________________________________________________________
dense_38 (Dense)             (None, 100)               6500      
_________________________________________________________________
activation_26 (Activation)   (None, 100)               0         
_________________________________________________________________
dense_39 (Dense)             (None, 50)                5050      
_________________________________________________________________
Total params: 13,854
Trainable params: 13,854
Non-trainable params: 0
_________________________________________________________________
layer_idx = utils.find_layer_idx(M1, 'dense_39')
sm1 = visualize_saliency(M1, layer_idx, seed_input=new_seed_input, filter_indices=None)  #new_seed_input is of shape (1,35)
print sm1
> [0 0 127]

Not sure where is the problem. Any help would be really appreciated. Thanks!

**Comment by subhashis** [comment]
I updated my keras-vis version to the latest version. The output of the visualize_saliency( ) is now just a single scalar value instead of the vector of size 35 (which is the size of my input vector). @keisen is this the expected outcome for the api call I made (above)

**Comment by subhashis** [comment]
@keisen I don't think the problem has been solved yet. 

With an input vector of size 35 the expected dimension of the saliency map is 35 as well. But currently, it is returning just a single scalar value.

On inspecting the visualize_saliency_with_losses( ) function I saw that the last two lines are
`grads = np.max(grads, axis=channel_idx)
    return utils.normalize(grads)[0]`

before updating grads, its dimension was (1,35), which actually matches with my input vector dimension.

**Comment by keisen** [comment]
@subhashis , Thanks! 

I created the PR #137 to fix this issue.
So please make sure of what there is no your problem in this PR.

* PullRequest
   * https://github.com/raghakot/keras-vis/pull/137
* Source
   * https://github.com/keisen/keras-vis
   * branch: `issues/#135`

**Comment by keisen** [comment]
Sorry, I forgot to mention one thing.

* Usage
   * `visualize_saliency_with_losses(input_tensor, losses, seed_input, keepdims=True)`
