### ISSUE TITLE
ImportError: No module named vis.visualization

### ISSUE THREAD

**Issue by a6225301** [raghakot/keras-vis#156]
![image](https://user-images.githubusercontent.com/22911232/49687029-0f67c780-fb38-11e8-92f2-c5fdc7c37310.png)
Hi, i have used the pip install keras-vis to install this package, and it seems work well. But when i try to implement the example of minist  attention, it occurred the error with ‘ImportError: No module named vis.visualization'.

**Comment by TJROY** [comment]
pip install keras-vis

**Comment by mohammadjavadnouri** [comment]
I have the same issue.
Tried: conda install keras-vis but it even couldn't find the package.

**Comment by Curovearth** [comment]
`pip install keras-vis` worked upto some extent also tried` pip install tf-keras-vis` ... worked

**Comment by anubratabhowmick** [comment]
Tried both pip install keras-vis and pip install tf-keras-vis .. Didn't work..

**Comment by RegmiYogesh** [comment]
pip install keras-vis working, thanks a lot

**Comment by Benblue3** [comment]
pip install tf-keras-vis working!! thx a lot!!!
