### ISSUE TITLE
Uint 8 Requirement/Image Preprocessing

### ISSUE THREAD

**Issue by pGit1** [raghakot/keras-vis#16]
These seems to be a killer flaw with this wonderful tool. Running the demo saliency map demo code runs perfect but it assumes the dtype of the image array is uint8. Any other dtype causes an error when ran. 

How to get around this? What happens when your problem has images that have been preprocessed (like img_array/255 and img_array.dtype='float32')? The model may give bad predictions on image arrays that are not in the same preprocssed formats used to train the model. Is there any way around this? Hoping for help from anyone...

**Comment by raghakot** [comment]
That's a good point. So, the heatmap could have specific bounds and dtype then? I can certainly change the API to accept these params to deprocess the image.

Another option might be to infer these based on seed_img, but i dont think i can get the min/max bounds from that. I can certainly infer dtype.

The third option is to assume bounds to always be 0-1, float32 or 0-255, uint8. That would keep the API simpler with less params.

Thoughts?

**Comment by pGit1** [comment]
I would just LOVE to use this API with any arbitrary model I build and
preprocessed image. I think that is what will make this truly powerful. In
general an API like
'cam_map(model,image,penultimate_conv_layer,model_class_prediction)', where
on could then resize to the original image size and visualize the CAM
mapping would be amazing. Basically what you have now but with ultimate
flexibility.

**Comment by mm-manu** [comment]
float32 0-1 range is the most common case, isnt't it?
