### ISSUE TITLE
Has `Jitter()` been removed?

### ISSUE THREAD

**Issue by zixuanweeei** [raghakot/keras-vis#161]
I ran the tutorial in the section of *Generating animated gif of optimization progress*, and it told me that `Jitter()` cannot be imported.

**Comment by keisen** [comment]
Can you tell us  the versions of libraries such as Python, Keras, Backend of Keras and keras-vis?
And will you please paste the error stacktrace here?

**Comment by keisen** [comment]
Same problem: #155

**Comment by zxweeei** [comment]
This is my error traceback.
```
Using TensorFlow backend.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-2be6919386a4> in <module>()
      1 from vis.losses import ActivationMaximization
      2 from vis.regularizers import TotalVariation, LPNorm
----> 3 from vis.modifiers import Jitter
      4 from vis.optimizer import Optimizer
      5 

ModuleNotFoundError: No module named 'vis.modifiers'
```

**Comment by keisen** [comment]
@zxweeei , Thank you.
I created a PullRequest for fixing the problem.
For details, see PRs/ #162 .

**Comment by Selimonder** [comment]
`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-48-b1463f24cb3f> in <module>()
      1 from vis.losses import ActivationMaximization
      2 from vis.regularizers import TotalVariation, LPNorm
----> 3 from vis.modifiers import Jitter
      4 from vis.optimizer import Optimizer
      5 

ModuleNotFoundError: No module named 'vis.modifiers'

---------------------------------------------------------------------------`

still experiencing this issue (0.4.1)

**Comment by senaras** [comment]
Jitter is moved to input_modifiers, therefore you need to update the line:

from vis.input_modifiers import Jitter
