### ISSUE TITLE
NameError: name 'osp' is not defined

### ISSUE THREAD

**Issue by rahulrkumar9000** [raghakot/keras-vis#179]
import keras

from vis.visualization import visualize_activation

Using TensorFlow backend.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\Anaconda3\envs\cv\lib\site-packages\skimage\__init__.py in <module>
    161     try:
--> 162         from ._shared import geometry
    163         del geometry

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

NameError                                 Traceback (most recent call last)
<ipython-input-1-60e1eef16870> in <module>
      1 import keras
      2 
----> 3 from vis.visualization import visualize_activation

~\Anaconda3\envs\cv\lib\site-packages\vis\visualization\__init__.py in <module>
      2 
      3 
----> 4 from .activation_maximization import visualize_activation_with_losses
      5 from .activation_maximization import visualize_activation
      6 

~\Anaconda3\envs\cv\lib\site-packages\vis\visualization\activation_maximization.py in <module>
      4 from keras import backend as K
      5 
----> 6 from ..losses import ActivationMaximization
      7 from ..optimizer import Optimizer
      8 from ..regularizers import TotalVariation, LPNorm

~\Anaconda3\envs\cv\lib\site-packages\vis\losses.py in <module>
      2 
      3 from keras import backend as K
----> 4 from .utils import utils
      5 
      6 

~\Anaconda3\envs\cv\lib\site-packages\vis\utils\utils.py in <module>
     12 from .. import backend
     13 
---> 14 from skimage import io, transform
     15 from collections import Iterable
     16 from keras import backend as K

~\Anaconda3\envs\cv\lib\site-packages\skimage\__init__.py in <module>
    163         del geometry
    164     except ImportError as e:
--> 165         _raise_build_error(e)
    166     # All skimage root imports go here
    167     from .util.dtype import (img_as_float32,

~\Anaconda3\envs\cv\lib\site-packages\skimage\__init__.py in _raise_build_error(e)
    136 def _raise_build_error(e):
    137     # Raise a comprehensible error
--> 138     local_dir = osp.split(__file__)[0]
    139     msg = _STANDARD_MSG
    140     if local_dir == "skimage":

NameError: name 'osp' is not defined

**Comment by keisen** [comment]
Thank you for your report.

> ImportError: DLL load failed: The specified module could not be found.
> During handling of the above exception, another exception occurred:

However, it seems a problem of Anaconda or your Windows environment.
I don't use either Anaconda and Windows, so I can't suggest any good idea, sorry.

We hope you can enjoy keras-vis.
Let us know to feel free when you find any problem about keras-vis.
