### ISSUE TITLE
i keep getting no module named losses.

### ISSUE THREAD

**Issue by MohmadAyman** [raghakot/keras-vis#19]
I guess this might be a nive mistake but i couldnt find help anywhere, 
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-42-41c13b054a82> in <module>()
      5 from vis.utils import utils
      6 from vis.utils.vggnet import VGG16
----> 7 from vis.visualization import visualize_saliency
      8 
      9 

/home/m/.local/lib/python3.5/site-packages/vis/visualization.py in <module>()
      3 from keras import backend as K
      4 
----> 5 from losses import ActivationMaximization
      6 from optimizer import Optimizer
      7 from regularizers import TotalVariation, LPNorm

ImportError: No module named 'losses'
```
i tried adding a file named losses and added the code in the readme of the repo, i then got another error saying ```no module utils named utils```.

**Comment by DylanCope** [comment]
I'm assuming you used pip to install the package? The pip link hasn't been updated so you should clone the repository and directly use the code. Either add the location of the repository to your PYTHONPATH or copy and paste the source files into your project.

That fixed the problems you're having, but you will probably still run into a few problems with the code itself. I found several functions just don't work so you have to fix them.

**Comment by raghakot** [comment]
I fixed various issues recently and also updated the pip package. Let me know if this is still an issue.

**Comment by vitasiku** [comment]
Still an issue for

- pip 9.0.1
- python 3.6.1
- MacOS Siera 10.12.6

**Comment by vitasiku** [comment]
Still an issue
pip 9.0.1
python 3.6.1
MacOS Siera 10.12.6

**Comment by mlizhardy** [comment]
double check the structure of your imports for example:
from vis.modifiers import Jitter

should be:
from vis.input_modifiers import Jitter

**Comment by sulthanashafi** [comment]
@MohmadAyman ,have you solved this problem.Iam incurring with the same problem.
File "ImageTraintwo.py", line 188, in <module>
    layer_idx = utils.find_layer_idx(model, layer_name)
NameError: name 'utils' is not defined

**Comment by MohmadAyman** [comment]
@sulthanashafi  Sorry I don't really remember if I did get it to work back then or not.

**Comment by aymenabid-lab** [comment]
The same problem
----> 6 from ..losses import ActivationMaximization


ModuleNotFoundError: No module named 'vis.losses'
