### ISSUE TITLE
cannot import visualize_saliency

### ISSUE THREAD

**Issue by go-bears** [raghakot/keras-vis#20]
I'm getting this error when trying to import visualize_saliencey

![image](https://cloud.githubusercontent.com/assets/6887377/24597292/bab46b58-17f9-11e7-80df-f35463c0127d.png)

I checked the Keras docs and it looks like K.image_data_format() is still valid attribute on the Keras backend. I'm wondering if this might be a Keras 1 to Keras 2 transition issue?

**Comment by raghakot** [comment]
Yes. This lib is now incompatible with keras < 2.0.
I transitioned everything to latest.
