### ISSUE TITLE
cannot import 'imresize'

### ISSUE THREAD

**Issue by abeepathak96** [raghakot/keras-vis#203]
- [ ] Check that you are up-to-date with the master branch of keras-vis. You can update with:
pip install git+git://github.com/raghakot/keras-vis.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by abeepathak96** [comment]
---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)

<ipython-input-41-773f8a8e3511> in <module>()
----> 1 from vis.visualization import visualize_activation
      2 from vis.utils import utils
      3 from keras import activations
      4 
      5 from matplotlib import pyplot as plt

1 frames

/usr/local/lib/python3.6/dist-packages/vis/visualization/__init__.py in <module>()
      5 from .activation_maximization import visualize_activation
      6 
----> 7 from .saliency import visualize_saliency_with_losses
      8 from .saliency import visualize_saliency
      9 from .saliency import visualize_cam_with_losses

/usr/local/lib/python3.6/dist-packages/vis/visualization/saliency.py in <module>()
      3 import numpy as np
      4 import matplotlib.cm as cm
----> 5 from scipy.misc import imresize
      6 
      7 from keras.layers.convolutional import _Conv

ImportError: cannot import name 'imresize'

**Comment by jwmandeville** [comment]
I had the same problem. I solved it by installing scipy 1.1.0. The version I had from pip was 1.3.0.

`pip install scipy==1.1.0`

**Comment by keisen** [comment]
Thanks @jwmandeville for reporting the solution.
And the api that caused ImportError was not used in keras-vis now.

We'll close this issue but if you find other problems corresponding this issue, feel free to reopen.

**Comment by kwende** [comment]
@keisen , I don't understand your comment: 

"And the api that caused ImportError was not used in keras-vis now."

I just installed keras-vis via pip and got this error going through the samples. Is it not supposed to happen anymore, or is the official solution what @jwmandeville found?

**Comment by keisen** [comment]
Hi, @kwende . Sorry for being unclear.
Now, keras-vis on PiPY has a problem that is no longer updated,  so please install and use keras-vis on github.

```
pip install -U -I git+https://github.com/raghakot/keras-vis.git
```
