### ISSUE TITLE
Saliency maps numpy divide

### ISSUE THREAD

**Issue by fredhohman** [raghakot/keras-vis#21]
I'm trying to reproduce the first example titled "Saliency maps" here:
https://raghakot.github.io/keras-vis/visualizations/attention/

But I'm running into the following error:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-3296fc2c6dec> in <module>()
     33 
     34     # Here we are asking it to show attention such that prob of `pred_class` is maximized.
---> 35     heatmap = visualize_saliency(model, layer_idx, [pred_class], seed_img)#, text=utils.get_imagenet_label(pred_class))
     36     heatmaps.append(heatmap)
     37 

/Users/fredhohman/anaconda/lib/python3.5/site-packages/vis/visualization.py in visualize_saliency(model, layer_idx, filter_indices, seed_img, text, overlay)
    162     # Smoothen activation map
    163     grads = utils.deprocess_image(grads[0])
--> 164     grads /= np.max(grads)
    165 
    166     # Convert to heatmap and zero out low probabilities for a cleaner output.

TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'B') according to the casting rule ''same_kind''
```

Looks like something with numpy division?

**Comment by raghakot** [comment]
Which version of numpy are you using? I cant reproduce this. Perhaps try a newer version of numpy?
The tests runs this example and its passing.

**Comment by fredhohman** [comment]
Thanks for the quick response!
I'm using `1.12.1`, but still isn't working.
Is there something else I can provide to help debug?

**Comment by andyfangdz** [comment]
I also had the same error. Looks like numpy had a breaking change in their API: https://github.com/numpy/numpy/issues/6464

My script also complained about missing a `imagenet_class_index.json` file. Here's the traceback:
```
Traceback (most recent call last):
  File "try.py", line 35, in <module>
    heatmap = visualize_saliency(model, layer_idx, [pred_class], seed_img, text=utils.get_imagenet_label(pred_class))
  File "/Users/andy/anaconda/lib/python3.5/site-packages/vis/utils/utils.py", line 185, in get_imagenet_label
    with open(os.path.join(os.path.dirname(__file__), '../../resources/imagenet_class_index.json')) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/andy/anaconda/lib/python3.5/site-packages/vis/utils/../../resources/imagenet_class_index.json'
``` 

Looks like there's an extra `..` in the path? I did find a file the file here, but the path should be `vis/utils/../../resources/imagenet_class_index.json`: https://github.com/raghakot/keras-vis/blob/master/resources/imagenet_class_index.json

**Comment by sakares** [comment]
In the file `visualization.py` under `vis/utils` directory which is based on your python site-package installation path,
I have made a change from 
`grads /= np.max(grads)` 
to 
`grads = np.true_divide(grads, np.max(grads))` 

However, I got a bug complained about:

` heatmap = cv2.applyColorMap(cv2.GaussianBlur(grads * 255, (3, 3), 0), cv2.COLORMAP_JET)`

> error: /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/colormap.cpp:501: error: (-5) cv::ColorMap only supports source images of type CV_8UC1 or CV_8UC3 in function operator()
on the line

any idea?

**Comment by raghakot** [comment]
Just letting you guys know that I looked into it. I have it fixed but i ended up making a whole bunch of efficiency improvements which i plan to get out together. I will try my best to get it wrapped up this weekend.

**Comment by raghakot** [comment]
Sorry this took a while. I just pushed a bunch of updates. These issues should now be fixed.

**Comment by raghakot** [comment]
Feel free to reopen if you continue to see the issue,

**Comment by kashiwale** [comment]
I am running activation_maximization in examples and getting following error:
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-6-bc0a2ea79b30> in <module>()
      8 
      9     # Reverse lookup index to imagenet label and overlay it on the image.
---> 10     img = utils.draw_text(img, utils.get_imagenet_label(idx))
     11     vis_images.append(img)
     12 

~\Anaconda3\envs\tensorflow\lib\site-packages\vis\utils\utils.py in get_imagenet_label(indices, join)
    276     global _CLASS_INDEX
    277     if _CLASS_INDEX is None:
--> 278         with open(os.path.join(os.path.dirname(__file__), '../../resources/imagenet_class_index.json')) as f:
    279             _CLASS_INDEX = json.load(f)
    280 

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\xxxxx\\Anaconda3\\envs\\tensorflow\\lib\\site-packages\\vis\\utils\\../../resources/imagenet_class_index.json'

vis package is updated to the most recent
