### ISSUE TITLE
 TypeError: __init__() got an unexpected keyword argument 'ragged'

### ISSUE THREAD

**Issue by sharpant** [raghakot/keras-vis#210]
I am using keras 2.2.4 and on running the below code

`model = utils.apply_modifications(model)`

I get the error:

` TypeError: __init__() got an unexpected keyword argument 'ragged' ` in the interfaces.py file.

Is there a solution? Thanks!

**Comment by sharpant** [comment]
I upgraded to Keras 2.3.0 (with TF 2.0.0) and the problem got solved

**Comment by AhmadSabbirChowdhury** [comment]
from tensorflow.keras import different packages, then it will not show these errors
