### ISSUE TITLE
TypeError: tuple indices must be integers or slices, not list

### ISSUE THREAD

**Issue by nehasoni3** [raghakot/keras-vis#212]
Hi geeks

I am trying to use 
`layer_idx = utils.find_layer_idx(model, 'activation_1')
model.layers[layer_idx].activation = activations.linear
model = utils.apply_modifications(model)
model.summary()`
for my custom model 

It gives me error `TypeError: tuple indices must be integers or slices, not list`

Please suggest solutions.
Looking forward for response.

**Comment by Raman1121** [comment]
Hey @nehasoni3 
I am facing the same problem. Did you find a solution to this?
