### ISSUE TITLE
object of type 'filter' has no len()

### ISSUE THREAD

**Issue by MSchuwalow** [raghakot/keras-vis#24]
Above error is thrown when trying to draw over an image with a callback.
Likely cause is https://github.com/raghakot/keras-vis/blob/master/vis/utils/utils.py#L40.
You probably want to return a list instead of a filter here.

**Comment by raghakot** [comment]
It's because filter returns an Iterator in python3. Fixed.

**Comment by jskDr** [comment]
It is not fixed. I still have the same error. If it is my special case, please ignore this comment. 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-cf4c2939ad83> in <module>()
----> 1 opt.minimize(max_iter=500, verbose=True, image_modifiers=[Jitter()], callbacks=[GifGenerator('opt_progress')])

C:\ProgramData\Anaconda3\lib\site-packages\vis\optimizer.py in minimize(self, seed_img, max_iter, image_modifiers, callbacks, verbose)
    132             # Trigger callbacks
    133             for c in callbacks:
--> 134                 c.callback(i, named_losses, overall_loss, grads, wrt_value)
    135 
    136             # Gradient descent update.

C:\ProgramData\Anaconda3\lib\site-packages\vis\callbacks.py in callback(self, i, named_losses, overall_loss, grads, wrt_value)
     59     def callback(self, i, named_losses, overall_loss, grads, wrt_value):
     60         img = utils.deprocess_image(wrt_value[0])
---> 61         img = utils.draw_text(img, "Step {}".format(i + 1))
     62         self.writer.append_data(img)
     63 

C:\ProgramData\Anaconda3\lib\site-packages\vis\utils\utils.py in draw_text(img, text, position, font, font_size, color)
    230 
    231     font_files = _find_font_file(font)
--> 232     if len(font_files) == 0:
    233         logger.warn("Failed to lookup font '{}', falling back to default".format(font))
    234         font = ImageFont.load_default()

TypeError: object of type 'filter' has no len()

**Comment by raghakot** [comment]
Did you try installing from source? I wrap the output as a `list` so it should have `len` in both python 2 and 3
