### ISSUE TITLE
NoneType Error with ResNet

### ISSUE THREAD

**Issue by sanjayaneja** [raghakot/keras-vis#26]
Hi I keep getting a NoneType error when trying to use visualize_cam for a pretrained resnet.  Code and error attached

def generate_cam(saved_model, layer_name, image_folder=constants.image_folder, show=True):
    """Generates a heatmap via grad-CAM method.
    First, the class prediction is determined, then we generate heatmap to visualize that class.
    """
    # Load Model network with trained weights
    model = load_model(saved_model)
    print('Model loaded.')
    # The name of the layer we want to visualize
    # (see model definition in vggnet.py)
    layer_name = str(layer_name)
    layer_idx = [idx for idx, layer in enumerate(model.layers) if layer.name == layer_name][0]
    for path in listdir_nohidden(image_folder):
        seed_img = utils.load_img(image_folder + '/' + path, target_size=(224, 224))
        # Convert to BGR, create input with batch_size: 1, and predict.
        bgr_img = utils.bgr2rgb(seed_img)
        img_input = np.expand_dims(img_to_array(bgr_img), axis=0)
        pred_class = np.argmax(model.predict(img_input))
        print(layer_idx)
        heatmap = visualize_cam(model, layer_idx-1, [pred_class], seed_img)
        if show:
            plt.axis('off')
            plt.imshow(heatmap)
            plt.show()
generate_cam(saved_resnet, 'dense_2')
Model loaded.
/Users/anaconda3/lib/python3.6/site-packages/skimage/transform/_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
180
Working on filters: [0]
Traceback (most recent call last):
  File "/Users/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-7867416d4604>", line 29, in <module>
    generate_cam(saved_resnet, 'dense_2')
  File "<ipython-input-9-7867416d4604>", line 23, in generate_cam
    heatmap = visualize_cam(model, layer_idx-1, [pred_class], seed_img)
  File "/Users/anaconda3/lib/python3.6/site-packages/vis/visualization.py", line 256, in visualize_cam
    heatmap = np.ones(shape=(rows, cols), dtype=np.float32)
  File "/Users/anaconda3/lib/python3.6/site-packages/numpy/core/numeric.py", line 192, in ones
    a = empty(shape, dtype, order)
TypeError: 'NoneType' object cannot be interpreted as an integer

**Comment by raghakot** [comment]
Can you give me access to the pretrained model? I cannot debug this any further without that.

**Comment by raghakot** [comment]
Actually, i think you might be running an older version. This line:
```heatmap = np.ones(shape=(rows, cols), dtype=np.float32)```
does not exist in the current code base. Update the lib and give it a shot?

**Comment by raghakot** [comment]
I am closing the issue. Feel free to reopen if this still causes issue on latest.
