### ISSUE TITLE
PyPi package needs update

### ISSUE THREAD

**Issue by NegatioN** [raghakot/keras-vis#30]
The PyPi package needs an update with [this commit](https://github.com/raghakot/keras-vis/commit/1d366cdf9b57467e5f655f453893151c6f26f027).
I can't get it working without building from source or hacking it into place.

Excited to try vis! :)

**Comment by raghakot** [comment]
Will do. Let me try to get a bunch of minor bug fixes before that.

**Comment by raghakot** [comment]
updated to 0.3.1. In general, pypi will easily drift from source.
