### ISSUE TITLE
izip has been removed in Python 3

### ISSUE THREAD

**Issue by IshitaTakeshi** [raghakot/keras-vis#32]
`utils. reverse_enumerate` doesn't work in Python 3 since`itertools.izip` has been removed.
https://github.com/raghakot/keras-vis/blob/master/vis/utils/utils.py#L55

Shall I replace it with just `zip`?

**Comment by raghakot** [comment]
Looks good. Thanks.

**Comment by IshitaTakeshi** [comment]
How can I run tests?

**Comment by raghakot** [comment]
Run `py.test tests/`
I guess I should setup a CONTRIBUTING.md file

**Comment by raghakot** [comment]
Any update on this? Since this is a small change, I can make it myself.

**Comment by IshitaTakeshi** [comment]
Could you do it?

**Comment by raghakot** [comment]
will do
