### ISSUE TITLE
OpenCV Dependency

### ISSUE THREAD

**Issue by DepthFirstSearch** [raghakot/keras-vis#34]
The comment on line 267 in the [visualization.py](https://github.com/raghakot/keras-vis/blob/master/vis/visualization.py#L267) file suggests to get rid of the OpenCV dependency.

Instead of OpenCV, one could use the [imresize](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.misc.imresize.html) function of the SciPy package. 

The code would change to:
`heatmap = imresize(heatmap, input_dims, interp='bicubic', mode='F')`

I have tested this successfully.

**Comment by raghakot** [comment]
Ah. Thanks. Feel free to submit a PR :)

**Comment by raghakot** [comment]
Since this is a simple change, I am pushing it for now. Thanks for the suggestion.
