### ISSUE TITLE
Divison by Zero

### ISSUE THREAD

**Issue by DepthFirstSearch** [raghakot/keras-vis#35]
Code in [visualize_cam](https://github.com/raghakot/keras-vis/blob/master/vis/visualization.py#L173) may perform a division by zero.

Assume we want to visualize the class 'cat' but `seed_img` is an image of a 'dog'. Hence, it is likely that the heatmap (weighted sum of the feature maps) is all negative (since `seed_img` does not contain any 'cat' features). In [line 272](https://github.com/raghakot/keras-vis/blob/master/vis/visualization.py#L272), we threshold the heatmap at 0. This produces an array containing only the value 0. In [line 273](https://github.com/raghakot/keras-vis/blob/master/vis/visualization.py#L273), we divide by the maximum of this array:
`heatmap /= np.max(heatmap)`
Hence, we would divide by zero. 

Two suggestions to solve this issue:
1. `heatmap /= np.max(heatmap) + epsilon`
2. `if np.max(heatmap) > 0: heatmap /= np.max(heatmap)`

**Comment by raghakot** [comment]
Thanks for pointing this out. The goal was to scale this between 0, 1. 
So the correct code should be:
```
heatmap = (heatmap - np.min(heatmap)) / (np.max(heatmap) - np.min(heatmap))
