### ISSUE TITLE
Heatmap Initialization

### ISSUE THREAD

**Issue by DepthFirstSearch** [raghakot/keras-vis#36]
I know, it doesn't really matter, but the `heatmap` in [visualize_cam](https://github.com/raghakot/keras-vis/blob/master/vis/visualization.py#L257) should be initialized as
`heatmap = np.zeros(shape=output_dims, dtype=K.floatx())`
instead of
`heatmap = np.ones(shape=output_dims, dtype=K.floatx())`

**Comment by raghakot** [comment]
Thanks for the catch.
