### ISSUE TITLE
Attention Map Error: module 'itertools' has no attribute 'izip'

### ISSUE THREAD

**Issue by wanting0wang** [raghakot/keras-vis#43]
Please see the attached screen-shot.
<img width="1059" alt="screen shot 2017-06-23 at 14 06 01" src="https://user-images.githubusercontent.com/25274600/27494899-de6749c6-581d-11e7-807c-6dce26463021.png">

Anyone knows how to solve it?
Thank you!

**Comment by raghakot** [comment]
It's fixed: https://github.com/raghakot/keras-vis/issues/32
Try installing from source. Pip might be out of date.

**Comment by wanting0wang** [comment]
Thanks for the reply. I checked the pip version.. the latest version on pypi is for py2 ; for py3 it's an old version. I tried to install from the source but there is a ModuleNotFoundError. Can you please update the py3 ver?

**Comment by wanting0wang** [comment]
Ok I managed to install it from the tar.tz package!
