### ISSUE TITLE
error font searching... in utils.py

### ISSUE THREAD

**Issue by nicezic0** [raghakot/keras-vis#44]
I got a font related error running the first sample code.

My env is , no GPU, Win10, conda with python 3.6

What I did first was downloading and install 'FreeSan.ttf' into system.

However, it didn't help out.

Then, I figured out what the problem was.

For me, this code, "len(font_files)" in vis/util/utils.py  causes the problem.

```
#    font_files = _find_font_file(font)
#     if len(font_files) == 0:
#         logger.warn("Failed to lookup font '{}', falling back to default".format(font))
#         font = ImageFont.load_default()
#     else:
#         font = ImageFont.truetype(font_files[0], font_size)
    font = ImageFont.load_default()
```

So, This is my way around, just using default font without checking a specific font.

FYI, Below is the traceback.

> Model loaded.
> Traceback (most recent call last):
> 
>   File "<ipython-input-1-1f9937b5cc71>", line 1, in <module>
>     runfile('C:/Users/User/Documents/tf/untitled4.py', wdir='C:/Users/User/Documents/tf')
> 
>   File "C:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "C:/Users/User/Documents/tf/untitled4.py", line 32, in <module>
>     opt.minimize(max_iter=500, verbose=True, image_modifiers=[Jitter()], callbacks=[GifGenerator('opt_progress')])
> 
>   File "C:\Anaconda3\lib\site-packages\vis\optimizer.py", line 134, in minimize
>     c.callback(i, named_losses, overall_loss, grads, wrt_value)
> 
>   File "C:\Anaconda3\lib\site-packages\vis\callbacks.py", line 61, in callback
>     img = utils.draw_text(img, "Step {}".format(i + 1))
> 
>   File "C:\Anaconda3\lib\site-packages\vis\utils\utils.py", line 232, in draw_text
>     if len(font_files) == 0:
> 
> TypeError: object of type 'filter' has no len()
>

**Comment by raghakot** [comment]
Are you using install from source? This was an old issue that happens because of python2/3 inconsistency and has been fixed. Feel free ti reopen if you see this in latest.

**Comment by Lijiachen1018** [comment]
I still got the problem, change the function in the utlis.py file

def _find_font_file(query):

    return list(filter(lambda path: query.lower() in os.path.basename(path).lower(), os.listdir('C:\Windows\Fonts')))

**Comment by keisen** [comment]
Hi @Lijiachen1018 .
Your problem was not reproduced in my test environment.
(But I have no Win10, so my environment is Win7, Python3.5 (Anaconda).)
Can you give me error log?

**Comment by Lijiachen1018** [comment]
Sorry, I was wrong, modify the def _find_font_file(query) not working.
I fond no FreeSan.ttf file in my system so I tried 'Arial.ttf' and 'Times New Roman.ttf', the former one works. Same error on 'Times New Roman.ttf' as using the default font.
-------------------------------------------------------------------------
Failed to lookup font 'Times New Roman.ttf', falling back to default

AttributeError                            Traceback (most recent call last)
<ipython-input-10-7afbd42cf238> in <module>()
     27     plt.axis('off')
     28     plt.imshow(stitched)
---> 29     plt.title(layer_name,font_size = 12)
     30     plt.show()

C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\pyplot.py in title(s, *args, **kwargs)
   1401 
   1402     """
-> 1403     return gca().set_title(s, *args, **kwargs)
   1404 
   1405 ## Axis ##

C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py in set_title(self, label, fontdict, loc, **kwargs)
    187         if fontdict is not None:
    188             title.update(fontdict)
--> 189         title.update(kwargs)
    190         return title
    191 

C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\text.py in update(self, kwargs)
    190         sentinel = object()  # bbox can be None, so use another sentinel.
    191         bbox = kwargs.pop("bbox", sentinel)
--> 192         super(Text, self).update(kwargs)
    193         if bbox is not sentinel:
    194             self.set_bbox(bbox)

C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\artist.py in update(self, props)
    900         try:
    901             ret = [_update_property(self, k, v)
--> 902                    for k, v in props.items()]
    903         finally:
    904             self.eventson = store

C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\artist.py in <listcomp>(.0)
    900         try:
    901             ret = [_update_property(self, k, v)
--> 902                    for k, v in props.items()]
    903         finally:
    904             self.eventson = store

C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\artist.py in _update_property(self, k, v)
    893                 func = getattr(self, 'set_' + k, None)
    894                 if not callable(func):
--> 895                     raise AttributeError('Unknown property %s' % k)
    896                 return func(v)
    897 

AttributeError: Unknown property font_size
