### ISSUE TITLE
MNIST example 

### ISSUE THREAD

**Issue by agodatt** [raghakot/keras-vis#46]
Put together a MNIST example for keras-vis here: https://gist.github.com/agodatt/70cb02b7172ffe2ed36020f5787daf18 , but I am not getting intuitive results. Could you point out why this is not working? Thanks!

**Comment by raghakot** [comment]
I added notebooks for MNIST in examples/ using your network architecture. Hope that clarifies how to debug such issues.

Feel free to reopen if you have more questions.
