### ISSUE TITLE
Atrribute credits in Readme

### ISSUE THREAD

**Issue by jacobgil** [raghakot/keras-vis#49]
Hi,
I've been following this project code from the beginning and think it's a nice effort.

Some of the ideas/code here were assisted with a few repositories of mine.
Specifically, 
https://github.com/jacobgil/keras-grad-cam
https://github.com/jacobgil/keras-filter-visualization
And now with the recent self driving car demo,
https://github.com/jacobgil/keras-steering-angle-visualizations

I think it would be fair if you attribute/give credit for this in the Readme.

Thanks,
Jacob

**Comment by raghakot** [comment]
Actually, I was inspired by keras blog on filter visualization. I did find your self driving blog while working on an issue that requested a way to visualize self driving car, so I will give credit for that. 

PS: I have some questions on that if you have time to discuss it. My implementation is actually a little different than yours.

**Comment by jacobgil** [comment]
Sure I"l be glad. Email me to jacob.gildenblat@gmail.com

**Comment by raghakot** [comment]
I added credits here: https://github.com/raghakot/keras-vis/blob/master/applications/self_driving/README.md

Let me know if you feel that i am missing attribution elsewhere.
PS: Would love it if you contribute PRs to this project. There are several implementations linked in the issues that are planned.
