### ISSUE TITLE
Use tempfile instead of hard-coded /tmp directory

### ISSUE THREAD

**Issue by FrankNiemeyer** [raghakot/keras-vis#58]
The directory where temporary Keras files are stored is hard-coded as `/tmp` in `tensorflow_backend.py` (line 81) and `utils.py` (line 110), which makes keras-vis fail on Windows. To fix this, `/tmp` should be replaced by either Python's `tempfile` or a customizable location.

**Comment by raghakot** [comment]
Ah yes. Thanks.
