### ISSUE TITLE
Segmentation fault (core dumped) when import vis.utils

### ISSUE THREAD

**Issue by samshipengs** [raghakot/keras-vis#61]
*Installation is up-to-date with the master branch of keras-vis. 
*Latest tensorflow and keras.
*python3
(running on ubuntu 16.04 LTS)

When I was trying to import in ipython3:
`from vis.utils import utils`
Ipython3 would just shut down and output "Segmentation fault (core dumped)".

Anyone experiences this?

**Comment by TimZaman** [comment]
I can hardly believe this is because of just `from vis.utils import utils`. Try to gather more clues.

**Comment by samshipengs** [comment]
> Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

`In [1]: from vis.utils import utils`
>Segmentation fault (core dumped)

@TimZaman This is what I got. What bothers me is it doesn't have any additional error message hinting what might be going on.

**Comment by raghakot** [comment]
Closing this issue for now. Feel free to reopen if this is recurring. It might have something to do with your tensorflow installation.
