### ISSUE TITLE
vis to keras-vis

### ISSUE THREAD

**Issue by TimZaman** [raghakot/keras-vis#64]
Hi! Congratulations on a really awesome repository. I made some very trippy images. 

I think `import vis` is a bit too generic. Is there any reason why we don't align this to `import keras-vis`?

To celebrate this great repo; here's my favourite filter I've found, reminds me of a retina:
![block3_conv2_065](https://user-images.githubusercontent.com/7721540/28519970-f5d5cbce-706d-11e7-98cc-6ba98d9b3502.jpeg).

(I also found usage of the repo `fchollet/deep-learning-models`, which has been deprecated, it's advised to use `fchollet/keras/applications`, where it's moved to.)

**Comment by raghakot** [comment]
Thanks :)

No reason in particular. I wanted to make the import module short. I eventually want to extend this beyond Keras (pytorch in particular) and might have to rename the repo etc. at that time. Will hold off renaming until then.
