### ISSUE TITLE
grad cam isn't working properly on inceptionv3 (similar to issue #23)

### ISSUE THREAD

**Issue by Abhijit-2592** [raghakot/keras-vis#65]
hey @sakares and @raghakot  , I am having a similar issue. Grad-cam isn't working properly in inceptionv3.
I did the same tutorial which Raghakot gave with only difference being I used Inceptionv3 instead of vgg16 and my Grad-cam isn't working properly.

![image](https://user-images.githubusercontent.com/29851832/28556902-f29ab0be-7126-11e7-816f-cde41c149603.png)

I manually set the penultimate_layer_idx = 299 ('conv2d_94'). Still the same result

**update:** guided grad-cam and relu grad-cam arn't working properly. only vanilla-grad-cam is working.
@raghakot  could you please explain why? I am, kinda stuck here

**Comment by sakares** [comment]
@Abhijit-2592 May I ask you to upload your result on vanilla-grad-cam, please?

Also, I never see the idea behind vanilla-grad-cam yet. please feel free to drop any reference.

**Comment by Abhijit-2592** [comment]
Kindly look at the notebook [here](https://github.com/Abhijit-2592/Keras-custom-callbacks/blob/master/how%20to%20use%20grad-cam%20in%20inceptionv3_copy.ipynb).
Using the pre-processing function is mandatory here. If not used it gives chaotic results. And if other than vanilla if you use relu or guided the results are chaotic.
More over in your issue #23 you suggested that penultimate layer should be 299. even that works. But for more accurate results you should use 310. I have shown both the heat maps you can see the difference easily.

**Comment by sakares** [comment]
@Abhijit-2592 Sorry, I have forgot to mentioned about issue #23 . Not sure if it can helps.

**Comment by Abhijit-2592** [comment]
@sakares  ya I just now saw that. I have implemented that in my code already
