### ISSUE TITLE
Return heatmaps instead of color-mapped results

### ISSUE THREAD

**Issue by FrankNiemeyer** [raghakot/keras-vis#67]
Is there a particular reason why `visualize_saliency_with_losses` and `visualize_cam_with_losses` returns a color-mapped result instead of the heatmap/grads?

I would suggest returning the result before mapping to a specific colormap like "jet".

See
https://github.com/raghakot/keras-vis/blob/master/vis/visualization/saliency.py#L83
https://github.com/raghakot/keras-vis/blob/master/vis/visualization/saliency.py#L196

**Comment by raghakot** [comment]
That's a good point. Will change it.

**Comment by LennartPiro** [comment]
@raghakot could you please make a new release and push it to PyPI? Would be great to have this fix when using pip. Thanks!

**Comment by akuehlka** [comment]
@raghakot, I'd just like you to know that I spent 2 days of work to find out that release 0.4.1 from github is different from release 0.4.1 from PyPI. Thanks @LennartPiro for pointing that out.
