### ISSUE TITLE
How can i install keras-vis in conda environment?

### ISSUE THREAD

**Issue by csh412** [raghakot/keras-vis#69]
Hi, I like to use keras-vis in jupyter notebook env

So I tried installing keras-vis in conda as below:

![1](https://user-images.githubusercontent.com/22813788/28789620-024b397c-7661-11e7-9d94-66c2dd440f09.jpg)

However, as you can see package was not found...

How can i install keras-vis in conda env? Thank you

**Comment by Ragitagha** [comment]
Dear Support,
this issue should be still open, keras-vis is still not available via conda install.
Please provide us with some more information!

Best regards!

**Comment by csh412** [comment]
I solved this problem using git clone method

$ git clone https://github.com/raghakot/keras-vis
$ cd keras-vis
$ git checkout Branch # where Branch is the desired branch

Now I can use keras-vis library!

**Comment by Ragitagha** [comment]
Hiho, 
but can you use it inside spyder too? 
as global conda install?
Best regards

**Comment by yuval-harpaz** [comment]
I got one step ahead, My system ipython (from bash terminal) is the same ipython I use in spyder. So in bash terminal I cd into the cloned repo and ran:
`sudo ipython setup.py install`
Now I can work with the notebook and import vis in spyder. However, while node 20 gives a nice bird on the notebook, it gives pseudo-random noise in spyder. Am I missing some optimization file?

**Comment by soumendra** [comment]
Any solutions yet? The package is also not in conda-forge etc.

**Comment by macheski** [comment]
https://pypi.org/project/keras-vis/#files
download and pip install
